name: CI

on:
  push:
    branches: [ master ]

jobs:
  test-build-deploy:
    name: âœ… Test, ğŸ› ï¸ Build & ğŸ“¦ Deploy
    runs-on: ubuntu-latest

    steps:
    - name: âš™ï¸ Checkout
      uses: actions/checkout@v2

    - name: âš™ï¸ Setup node
      uses: actions/setup-node@v1
      with:
        node-version: 12

    - name: ğŸ› ï¸ Build & âœ… Test
      run: |
      npm install gatsby-cli -g
      npm ci
      sed -i'' -e 's|/latest?format=json|?format=json|g' node_modules/gatsby-source-medium/gatsby-node.js
      npm run build
      npm run test

    - name: ğŸ“¦ Deploy
      uses: netlify/actions/cli@master
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      with:
        args: deploy --dir=public --prod
        secrets: '["NETLIFY_AUTH_TOKEN", "NETLIFY_SITE_ID"]'
